### ISSUE TITLE
Consider locating terminal apps by bundle ID rather than hard coded paths

### ISSUE THREAD

**Issue by jfieber** [belcar-s/nova-external-terminal#1]
```shell
% mdfind kMDItemCFBundleIdentifier = com.googlecode.iterm2
/Users/jfieber/Applications/iTerm.app
```

This would also allow filtering the terminal list by those actually installed.

[This](https://github.com/jfieber/Marked2.novaextension/blob/9ad00454b3c82d0d2695f7c9338b44f574f5bdf5/Scripts/main.js#L132-L147) has a more complicated context of picking between multiple installed versions of an app, but is somewhat applicable.

**Comment by belcar-s** [comment]
Thanks; I didn’t know about this.

**Comment by kopischke** [comment]
Apologies for jumping into this issue, and do tell if you would prefer me to open separate ones, but I have two more remarks that may be apposite to the issue at hand, i.e. how to open the correct application without hardcoding paths: 

1. Even if you do not use bundle identifiers, `open` works with just the application name if used with the `-a` flag: `open . -a Terminal` will open the current directory in Apple’s Terminal.app (and without a path, it will open it in its default start directory). The system will do its own lookup, so installations outside the hardcoded path will work. However, using bundle identifiers (e.g. `open . -b com.apple.Terminal`), as John suggested, has the added advantage of being independent of the user renaming the application in question, so it’s even more robust.
2. The special treatment of Alacritty also isn’t necessary: `open` has an `--args` flag which passes everything that follows it as an argument to the executable being started. Some “platform independent” apps have difficulties with this, but a quick test shows Alacritty 0.8.0 doing what is expected when started with `open -a Alacritty --args --working-directory <dir>`. In this case, you get rid of the reliance on the command line `alacritty`, which isn’t installed if you use Alacritty.app out of the DMG offered for download.

**Comment by belcar-s** [comment]
Thank you for your helpful comments @kopischke and @jfieber. I think I've made the changes you described.

**Comment by kopischke** [comment]
Very cool, looking really nice. One remark, though: last time I looked, Nova’s `require`, unless Node’s, did not work with anything but modules; are you sure your bundle identifiers are loaded? Be that as it may, the separate bundle identifier file isn’t actually needed: you can use two-item [Enum Values](https://docs.nova.app/extensions/preferences/#enum-values) in the preferences instead.

**Comment by pekenotsopeke** [comment]
@kopischke @jfieber Your suggestions are very clever, you seem to be very talented in this topic. Have a nice day!

**Comment by jfieber** [comment]
@belcar-s It works perfectly for me now, thanks!

**Comment by belcar-s** [comment]
> Very cool, looking really nice. One remark, though: last time I looked, Nova’s `require`, unless Node’s, did not work with anything but modules; **are you sure your bundle identifiers are loaded?**

They fortunately are, although that feature of `require` might be undocumented —I recall reading something similar.

**Comment by kopischke** [comment]
@belcar-s good to know; I distinctly remember hitting a wall when I tried `require`ing a JSON file back with Nova … 2, I think (I have had a shim for that in my scripts ever since). Anyway, as I mentioned, in your specific case, you don’t actually need the extra file, but it’s a good feature to have around.
